### ISSUE TITLE
Heating Threshold Error in Logs

### ISSUE THREAD

**Issue by richardmarr** [jxg81/homebridge-actron-que#17]
Seeing this error in the logs

![IMG_0487](https://github.com/jxg81/homebridge-actron-que/assets/26127892/6589833d-051e-4a54-bebb-9e2fc0e06d3d)

**Comment by jxg81** [comment]
Can you provide your config.json settings for the plugin.
IMPORTANT!!!
please remove user, password and any other sensitive details.

**Comment by richardmarr** [comment]
![IMG_0488](https://github.com/jxg81/homebridge-actron-que/assets/26127892/f45ff144-4085-49c8-bc49-00c4188dcfa7)

**Comment by jxg81** [comment]
This config all looks ok - were these errors a one off or are the occurring continuously?
The Actron API server can be very unreliable. I added some logic a while back to validate schema in responses but had to make it a little bit loose as there a times where incomplete info is returned on polling (random and usually occurs in short repeated durations). Anyway - let me know if this is happening continuously and we can look at some debug.

**Comment by richardmarr** [comment]
Looks like it was a one off and was not happening later yesterday nor today

Thanks again
Sent from my iPhone

On 21 Jan 2024, at 4:46 pm, Julian Greensmith ***@***.***> wrote:

﻿

This config all looks ok - were these errors a one off or are the occurring continuously?
The Actron API server can be very unreliable. I added some logic a while back to validate schema in responses but had to make it a little bit loose as there a times where incomplete info is returned on polling (random and usually occurs in short repeated durations). Anyway - let me know if this is happening continuously and we can look at some debug.

**Comment by jxg81** [comment]
Thanks for confirming - will close this out now.

**Comment by richardmarr** [comment]
Thanks so much
Sent from my iPhone

On 22 Jan 2024, at 9:18 am, Julian Greensmith ***@***.***> wrote:

﻿

Thanks for confirming - will close this out now.
