### ISSUE TITLE
Support for ActronAir Neo Controller/App

### ISSUE THREAD

**Issue by brades1607** [jxg81/homebridge-actron-que#8]
**Is your feature request related to a problem? Please describe.**
Integration of this plugin with ActronAir's latest controller, Neo.

**Describe the solution you'd like**
Integration of this plugin with ActronAir's latest controller, Neo.

**Describe alternatives you've considered**
Attempted to try with the Que plugin with the login details from the Neo app, but no luck

**Additional context**

**Comment by jxg81** [comment]
Hi @brades1607 I wrote this plugin based on interrogation of my own que system operation. I suspect that the entire API component would need to be rewritten to work with the Neo API which i do not have the resources to investigate.
Please feel free to fork the repo, you will be able to reuse much of the framework but you would need to replace the Que API interface with the relevant Neo API. Happy to give you some pointers if you're keen to pick it up.
